name: TokensAPI
version: 1.0.1
author: Terpz710
api: 5.0.0
main: terpz710\tokensapi\TokensAPI

permissions:
  tokensapi.addtokens:
    default: op
  tokensapi.removetokens:
    default: op
  tokensapi.settokens:
    default: op
  tokensapi.paytokens:
    default: true
  tokensapi.mytokens:
    default: true
  tokensapi.seetokens:
    default: true
  tokensapi.topbalances:
    default: true
